version: "3.4"

services:
  api:
    image: saleor:runtime
    restart: unless-stopped
    environment:
      - DEFAULT_CHANNEL_SLUG
      - DATABASE_URL
      - DEFAULT_FROM_EMAIL
      - CELERY_BROKER_URL
      - SECRET_KEY
      - JAEGER_AGENT_HOST
      - STOREFRONT_URL
      - DASHBOARD_URL
      - ALLOWED_HOSTS
    network_mode: "host"
    stdin_open: true
    tty: true
    volumes:
      - ./saleor/:/app/saleor:Z
      - ./templates/:/app/templates:Z
      - ./tests/:/app/tests
      # shared volume between worker and api for media # TODO: FUCK
      - saleor-media:/app/media
    command: python manage.py runserver [::]:8000

  worker:
    image: saleor:runtime
    restart: unless-stopped
    environment:
      - DEFAULT_CHANNEL_SLUG
      - DATABASE_URL
      - DEFAULT_FROM_EMAIL
      - CELERY_BROKER_URL
      - SECRET_KEY
    network_mode: "host"
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    volumes:
      - ./saleor/:/app/saleor:Z,cached
      - ./templates/:/app/templates:Z,cached
      # shared volume between worker and api for media # TODO: FUCK
      - saleor-media:/app/media

  jaeger:
    network_mode: "host"
    image: jaegertracing/all-in-one
    restart: unless-stopped

  mailhog:
    network_mode: "host"
    image: mailhog/mailhog
    restart: unless-stopped

volumes:
  saleor-media:
